"""Adicionando restrição na exclusão de salário

Revision ID: 55dca8558627
Revises: 
Create Date: 2025-02-07 11:50:36.161655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55dca8558627'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mao_de_obra', schema=None) as batch_op:
        batch_op.drop_constraint('mao_de_obra_salario_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'salario', ['salario_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mao_de_obra', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('mao_de_obra_salario_id_fkey', 'salario', ['salario_id'], ['id'])

    # ### end Alembic commands ###
